services:
  - type: web
    name: usps-tracker
    env: node
    region: oregon
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    plan: free